[package]
name = "particle-argon"
version = "0.1.0"
edition = "2018"
authors = ["Rukai <rubickent@gmail.com>"]
description = "Particle Argon dev board support crate"
keywords = ["arm", "cortex-m", "wifi"]
repository = "https://github.com/rukai/particle-argon"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nrf52840-hal = { version = "0.12.1", features = ["rt"] }

[dev-dependencies]
cortex-m = "0.7.2"
cortex-m-rt = "0.6.12"
rtt-target = {version = "0.3.0", features = ["cortex-m"] }

[dependencies.embedded-hal]
version = "0.2.3"
features = ["unproven"]
